## Ricardo Figueroa CU 112714
## Tarea 4
### Algoritmo de Dijkstra
### Algoritmo para multiplicación de matrices

Primero vamos a recordar como se construye un arbol:

In [52]:
import collections
import numpy as np

In [193]:
B=dict(name='B', distance=1000, children=[])

In [194]:
A=dict(name='A', distance=1000, children=[])

In [195]:
C=dict(name='C', distance=1000, children=[])

In [196]:
D=dict(name='D', distance=1000, children=[])

In [197]:
E=dict(name='E', distance=1000, children=[])

In [198]:
F=dict(name='F', distance=1000, children=[])

In [199]:
A['children'] = [B,C]

In [200]:
B['children'] = [C,D]

In [201]:
C['childred'] = [D]

In [202]:
E['children'] = [F]

In [203]:
F['children'] = [C]

In [204]:
for i in A['children']:
    print i['name']

B
C


In [205]:
def all_paths(graph, result):
    children = graph['children']
    print(graph['name'])
    result.append(graph['name'])
    for i in children:
        all_paths(i, result)
    return result

In [206]:
all_paths(A, [])

A
B
C
D
C


['A', 'B', 'C', 'D', 'C']

Vamos a crear la clase 'Graph'

In [242]:
class Graph:
  def __init__(self):
    self.nodes = set() ##creates a set {}
    self.edges = collections.defaultdict(list) 
    self.distances = {}

  def add_node(self, value):
    self.nodes.add(value)

  def add_edge(self, from_node, to_node, distance):
    self.edges[from_node].append(to_node)
    self.edges[to_node].append(from_node)
    self.distances[(from_node, to_node)] = distance
    self.distances[to_node, from_node] = distance

In [243]:
graph = Graph()

In [244]:
graph.add_node("s")

In [245]:
graph.add_node("b")

In [246]:
graph.add_node("c")

In [247]:
graph.add_node("d")

In [248]:
graph.add_node("e")

In [249]:
graph.add_node("t")

In [250]:
print(graph.nodes)

set(['c', 'b', 'e', 'd', 's', 't'])


In [251]:
graph.add_edge('s','b',4)

In [252]:
graph.add_edge('s','c',2)

In [253]:
graph.add_edge('b','c',1)

In [254]:
graph.add_edge('b','d',5)

In [255]:
graph.add_edge('c','d',8)

In [256]:
graph.add_edge('c','e',10)

In [257]:
graph.add_edge('d','e',2)

In [258]:
graph.add_edge('d','t',6)

In [259]:
graph.add_edge('e','t',2)

In [260]:
print(graph.distances)

{('b', 'c'): 1, ('s', 'b'): 4, ('t', 'd'): 6, ('c', 's'): 2, ('e', 'd'): 2, ('s', 'c'): 2, ('d', 'e'): 2, ('b', 's'): 4, ('c', 'b'): 1, ('d', 't'): 6, ('t', 'e'): 2, ('e', 't'): 2, ('e', 'c'): 10, ('c', 'd'): 8, ('d', 'b'): 5, ('d', 'c'): 8, ('c', 'e'): 10, ('b', 'd'): 5}


In [261]:
print(graph.edges)

defaultdict(<type 'list'>, {'c': ['s', 'b', 'd', 'e'], 'b': ['s', 'c', 'd'], 'e': ['c', 'd', 't'], 'd': ['b', 'c', 'e', 't'], 's': ['b', 'c'], 't': ['d', 'e']})


In [262]:
print(graph.edges['c'])

['s', 'b', 'd', 'e']


In [263]:
print(graph.distances)

{('b', 'c'): 1, ('s', 'b'): 4, ('t', 'd'): 6, ('c', 's'): 2, ('e', 'd'): 2, ('s', 'c'): 2, ('d', 'e'): 2, ('b', 's'): 4, ('c', 'b'): 1, ('d', 't'): 6, ('t', 'e'): 2, ('e', 't'): 2, ('e', 'c'): 10, ('c', 'd'): 8, ('d', 'b'): 5, ('d', 'c'): 8, ('c', 'e'): 10, ('b', 'd'): 5}


In [264]:
dijsktra(graph, "s")

({'b': 4, 'c': 2, 's': 0}, {'b': 's', 'c': 's'})

In [265]:
def calc_distance(graph, node1, node2):
    return graph.distances[(node1,node2)] 

In [266]:
calc_distance(graph, 'b', 'c')

1

In [267]:
calc_distance(graph, 'c', 'd')

8

In [268]:
graph.edges['d']

['b', 'c', 'e', 't']

In [284]:
def dijsktra2(graph, initial_node, final_node):
    current_node = initial_node
    visited_nodes = {}
    path = []
    path.append(current_node)
    while(current_node != final_node):
        current_node_edges = graph.edges[current_node]
        visited_distances = {}
        for i in current_node_edges:
            if i not in visited_nodes:
                    temp_distance = calc_distance(graph, current_node, i)
                    visited_distances[i]=temp_distance
        if(visited_distances):
            min_next = reduce(lambda x,y: x if visited_distances[x]<=visited_distances[y] else y, visited_distances.iterkeys())
            next_object_distance = visited_distances[min_next]
            next_object = {}
            next_object[next_object_distance] = current_node
            visited_nodes[current_node]=current_node
            current_node = min_next
        path.append(current_node)
    return path

In [53]:
dijsktra2(graph, 's', 't')

['s', 'c', 'b', 'd', 'e', 't']

In [58]:
array = np.array([1])

In [69]:
array = np.append(array,1)

In [70]:
array

array([1, 1])

## Cadena de multiplicacion de matrices
Se dan una secuencia (cadena) <A1 , A2,...,An> de n matrices para ser multiplicadas y deseamos multiplicar el producto
A1A2...An. La manera en como se acomode el agrupamiento de la multiplicacion por las matrices es muy importante y puede afectar
significativamente el desempeno del algoritmo. A continuacion se presenta el algorimto general de multiplicacion de matrices:

Se define el costo de multiplicacion de matrices por la variable 'scalar_mult'

In [252]:
def mat_mult_simple(mat_a, mat_b):
    scalar_mult = 0
    new_matrix = np.zeros((len(mat_a),len(mat_b[0])))
    for i in range(0, len(mat_a)):
        for j in range(0, len(mat_b[0])):
            for k in range(0,len(mat_a[0])):
                new_matrix[i][j] = new_matrix[i][j] + mat_a[i][k] * mat_b[k][j]
                scalar_mult = scalar_mult + 1
    return new_matrix,scalar_mult

Ejemplo a continuacion:

In [253]:
x = np.array([[4,2,4], [8,3,1]], np.int32)

In [254]:
y = np.array([[3,5], [2,8], [7,9]], np.int32)

In [255]:
x

array([[4, 2, 4],
       [8, 3, 1]], dtype=int32)

In [256]:
y

array([[3, 5],
       [2, 8],
       [7, 9]], dtype=int32)

In [257]:
print(mat_mult_simple(x,y))

(array([[44., 72.],
       [37., 73.]]), 12)


El tiempo de calculo esta dado por el numero de multiplicaciones escalares en la linea 6 del codigo.
En el caso del ejemplo simple es 12

Se describe el problema de la multiplicacion de matrices en cadena como sigue:
Dada una cadena de n matrices <A1, A2, ... An>, donde i = 1,2,3,...,n, la matriz Ai tiene una dimension pi-1 x pi,
encontrar una manera de agrupar las matrices por parentesis de una forma que se minimize el numero
de multiplicaciones escalares. Notar que no se estan multiplicando matrices. El fin es determinar el costo menor.

Antes de aplicar programacion dinamica al problema es importante mencionar que revisar todas las posibles agrupaciones
por parentesis no es una solucion eficiente. El numero de posibles soluciones es exponencial en n.

### Aplicando programacion dinamica

Teoricamente, el valor del costo minimo del agrupamiento de las matrices estan dado por la siguiente funcion:
m[i,j] = {0 si i=j, min{m[i,k] + m[k+1,j] + pi-1*pk*pj}, si i<j}.

Esta funcion recursiva consiste en partir en subconjuntos las matrices y encontrar soluciones optimas "locales". Sin embargo una solucion recursiva presenta similitudes con intentar de probar todas las combinaciones y es cara por definicion, por ello se utiliza una solucion con programacion dinamica.

Esta solucion asume que la matriz Ai tiene dimensiones pi-1*pi para i=1,2,...,n.
El input es la secuencia p=<p0,p1,...,pn>, donde p.length = n+1. Este metodo utiliza una table auxiliar
m[1...n,1...n] para guardar m[i,j] costos y otra tabla auxiliar s[1...n-1,2...n] para guardar el indice de k que logro una solucion optima al calcular m[i,j].

Para implementar la solucion este enfoque, se deben de determinar a que elementos de la tabla nos estamos refiriendo cuando calculemos m[i,j], el costo minimo asociado a las matrices i,...j. Por ejemplo para k=i, i+1,...j-1 la matriz Ai..k es el producto de k-i+1<j-i+1 matrices y la matriz Ak+1..j es el producto de j-k<j-i+1 matrices.

El algoritmo debe llenar en la tabla m de una forma que corresponda a resolver el problema del agrupamiento o "parentizacion" en cadenas de matrices de tamano creciente. A continuacion el algoritmo: